# DeepSource configuration file
# Learn how to configure: https://docs.deepsource.com/docs/configuration
version = 1
exclude_patterns = ["venv", "node_modules", "bower_components", "out", "bin", "build", "dist"]
test_patterns = ["**/test_*.py", "**/__tests__/**", "**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js", "**/*_test.go"]

[[analyzers]]
  name = "python"
  enabled = true

[[analyzers]]
  name = "javascript"
  enabled = true

[[analyzers]]
  name = "go"
  enabled = true

[[analyzers]]
  name = "rust"
  enabled = true
