name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run targeted tests (interception flow)
        run: |
          python -m pytest tests/test_intercept_flow.py -v
