name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv (fast dependency manager)
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt --no-deps; fi

      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          python -m pytest -q || python -m pytest -q -vv

      - name: Upload test results (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: ./.pytest_cache
          if-no-files-found: ignore
